#!/bin/sh
if grep -q Microsoft /proc/version ; then
  system_type="WSL1"
elif grep -q microsoft /proc/version ; then
  system_type="WSL2"
else
  system_type=$(uname -s)
fi

if [ "$system_type" = "Linux" ] || [ "$system_type" = "WSL1" ] || [ "$system_type" = "WSL2" ]; then
  # install zsh, zplug, neovim
  if ! command -v zsh > /dev/null 2>&1; then
    echo "Installing zsh..."
    sudo apt install zsh -y
    chsh -s $(which zsh)
  elif [ ! -f ${HOME}/.zplug/init.zsh ]; then
    echo "Installing zplug..."
    # curl -sL --proto-redir -all,https https://cdn.jsdelivr.net/gh/zplug/installer/installer.zsh | zsh
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  else
    echo "All packages are installed."
  fi
fi
